[Polkadot] Feedback fixes
Ledger-Coin-Integration-team/ledger-live-common pull request #25
Opened 2020-12-04 17:19 UTC by henri-ly

2020-12-07 10:47 UTC, rjarasson-ledger approved these changes

2020-12-07 10:47 UTC, rjarasson-ledger commented on src/api/polkadot/bisontrails.js
> +  const hash = `${slash.blockNumber}  `; // to be compatible with explorer
Why the spaces ?
I don't think this is intended.

2020-12-07 10:47 UTC, rjarasson-ledger commented on src/families/polkadot/js-estimateMaxSpendable.js
> +      "111111111111111111111111111111111HC1" ||
maybe switch the two ?
Because the || here is useless.

2020-12-07 10:47 UTC, rjarasson-ledger commented on src/errors.js
> +export const PolkadotBondNotEnoughBalanceBecauseDestinationNotCreated = createCustomErrorClass(
This error name is a bit too long, and confusing.

PolkadotBondMinimumAmount would be more appropriate, since there is no Destination when bonding, and that was the confusing part of the previous error.

2020-12-07 10:47 UTC, rjarasson-ledger commented on src/families/polkadot/test-dataset.js
> +                  amount: new PolkadotBondNotEnoughBalanceBecauseDestinationNotCreated(),
Don't forget to update error here too.

2020-12-07 10:47 UTC, rjarasson-ledger commented on src/api/polkadot/common.js
> +        "polkadot/pallet",
polkadot/api would be more contextual than "pallet" since there is no mention of such module or namespace in live-common.

2020-12-07 10:47 UTC, rjarasson-ledger commented on src/api/polkadot/bisontrails.js
> +    fee: BigNumber(extrinsic.partialFee || 0),
Are you sure we did not missed a case here ?

Did BisonTrails removed for sure fees when extrinsic is not signed by the synced account ?
I would have kept the condition "just in case".

Since IN operations seems to be read as `extrinsic.signer !== addr` i would expect the fees to be present anyway.

2020-12-07 10:47 UTC, rjarasson-ledger requested changes
oops not approved;

2020-12-07 10:49 UTC, henri-ly commented on src/families/polkadot/js-estimateMaxSpendable.js
> +      "111111111111111111111111111111111HC1" ||
It's just really tmp we need to have the ledgerjs  merged with the abandon seed it will be removed later

2020-12-07 10:53 UTC, rjarasson-ledger commented on src/families/polkadot/js-estimateMaxSpendable.js
> +      "111111111111111111111111111111111HC1" ||
ok !

2020-12-07 11:43 UTC, henri-ly commented on src/api/polkadot/bisontrails.js
> +    fee: BigNumber(extrinsic.partialFee || 0),
BT doesn't remove fees from extrinsic that is not signed by synced account :/ I have to add this or the sums of OPs wouldn't be the same : 
`  if (type === "BOND" && extrinsic.signer !== addr) {
    return null;
  }`

As I understand, in a basic idea we want to display fees for any operation that we received or we are doing.
But for the case of Bond, it will directly impact the sums of op since we are using
`op.fees` as value of reference

2020-12-07 11:59 UTC, rjarasson-ledger commented on src/api/polkadot/bisontrails.js
> +    fee: BigNumber(extrinsic.partialFee || 0),
Ah yes, forgot about the improvement "keep the fees for all operations"

2020-12-08 09:43 UTC, rjarasson-ledger approved these changes

2020-12-10 15:55 UTC, merged