Polkadot types
Ledger-Coin-Integration-team/ledger-live-common pull request #8
Opened 2020-09-23 14:02 UTC by henri-ly

2020-09-24 09:42 UTC, haammar-ledger reviewed
A few comments

2020-09-24 09:42 UTC, haammar-ledger commented on src/families/polkadot/types.js
> +  identity: string,
`identity` is probably going to be an object since it contains several fields, and we can add `judgementStatus` as well.
See https://wiki.polkadot.network/docs/en/learn-identity and https://substrate.dev/rustdocs/v2.0.0-rc6/pallet_identity/enum.IdentityField.html

2020-09-24 09:42 UTC, haammar-ledger commented on src/families/polkadot/types.js
> +|};
You can add a `nominators` array, that would be empty when querying all validators and would be filled only when querying 1 specific validator. Each nominator in the array would have his address and bonded amount, at least.

2020-09-24 09:42 UTC, haammar-ledger commented on src/families/polkadot/types.js
> +export type PolkadotUnbondings = {|
Should be singular I think.

2020-09-24 09:42 UTC, haammar-ledger commented on src/families/polkadot/types.js
> +export type PolkadotOperationMode = "send" | "bond" | "nominate" | "unbond"
We'll probably need a `"reward"` mode too, but maybe it already exists as not polkadot-specific?

2020-09-24 09:45 UTC, henri-ly commented on src/families/polkadot/types.js
> +|};
Not sure if it's revelant on a UI / UX side, but we can add it. I don't see any case that we will display the nominators of a validators

2020-09-24 09:46 UTC, henri-ly commented on src/families/polkadot/types.js
> +export type PolkadotOperationMode = "send" | "bond" | "nominate" | "unbond"
It will be added when I will work on claimReward i think, but nice catch

2020-09-24 09:56 UTC, rjarasson-ledger requested changes

2020-09-24 09:56 UTC, rjarasson-ledger commented on src/families/polkadot/types.js
> +export type PolkadotOperationMode = "send" | "bond" | "nominate" | "unbond"
Are those internal values we will use in Operation ?

If not, i would recommend using raw values in the form of "module.function" like "staking.bond" for instance.

Don't you add bondExtra and rebond ? or it's all under the "bond" mode ?

2020-09-24 09:56 UTC, rjarasson-ledger commented on src/families/polkadot/types.js
> +  rewardsPoint: number,
rewardPoints ?

2020-09-24 09:56 UTC, rjarasson-ledger commented on src/families/polkadot/types.js
> +  status: "active" | "inactive" | "waiting"
I would put this in a separate Type.

2020-09-24 09:56 UTC, rjarasson-ledger commented on src/families/polkadot/types.js
> +  nominatorCount: number,
nominatorsCount ?

2020-09-24 09:56 UTC, rjarasson-ledger commented on src/families/polkadot/types.js
> +  identity: string,
identity is an object with from raw rpc gives:

```
{
    "display": "Polkadot.pro - Realgar",
    "email": "hello@polkadot.pro",
    "judgements": [
      [
        1,
        {
          "Reasonable": null
        }
      ]
    ],
    "other": {},
    "riot": "@realgar:matrix.org",
    "twitter": "@propolkadot",
    "web": "https://polkadot.pro"
}
```

We should find a better format for judgments (maybe only a judgment status like "reasonnable"), and ignore other.

2020-09-24 09:56 UTC, rjarasson-ledger commented on src/families/polkadot/types.js
> +export type PolkadotValidator = {|
I don't understand this type.
Is this a nomination ?

2020-09-24 09:56 UTC, rjarasson-ledger commented on src/families/polkadot/types.js
> +  rewards: BigNumber,
rewards are given per-era, so this might be more complexe like an array of all rewards for each era, with information about it being claimed or not yet.

2020-09-24 09:56 UTC, rjarasson-ledger commented on src/families/polkadot/types.js
> +  isElected: boolean,
why not status giving kinda the same info ?

2020-09-24 09:57 UTC, haammar-ledger commented on src/families/polkadot/types.js
> +|};
It's in case we want to help the user chose between validators, by computing the minimum stake he needs to be in the 64 rewarded nominators for a given validator. This would be a nice-to-have feature for the Live, but we can try to do it just in case, maybe we won't use it indeed.

2020-09-24 10:01 UTC, henri-ly commented on src/families/polkadot/types.js
> +export type PolkadotOperationMode = "send" | "bond" | "nominate" | "unbond"
it will be use in the as a "mode" in the CLI (and frontend) something like
`ledger-live send --mode bond --amount 1.5`

So it's purely live side

For the bond we will catch if there's already an account with locked balance if not we will use the sender as the controller address

2020-09-24 10:03 UTC, henri-ly commented on src/families/polkadot/types.js
> +  identity: string,
We need to discuss with live and ui / ux designer to see how they want to display it. Imo display will be the only good field to display name.

2020-09-24 10:04 UTC, henri-ly commented on src/families/polkadot/types.js
> +export type PolkadotValidator = {|
Yes, it's the nomination

2020-09-24 10:05 UTC, henri-ly commented on src/families/polkadot/types.js
> +  rewards: BigNumber,
I think it's more rewards in a sense of "Pending rewards"

2020-09-24 10:06 UTC, henri-ly commented on src/families/polkadot/types.js
> +  isElected: boolean,
Yes we can I didn't think about it when I wrote it but it came later

2020-09-24 10:07 UTC, henri-ly commented on src/families/polkadot/types.js
> +|};
Probably going to discuss this with UI / UX too see if we can display the 64 in a mobile or in the modal of desktop, seems to be very challenging tho but I could be wrong

2020-09-24 11:59 UTC, haammar-ledger commented on src/families/polkadot/types.js
> +export type PolkadotValidator = {|
Yep can be renamed to `PolkadotNomination` to avoid confusion with `PolkadotValidatorItem`

2020-09-24 11:59 UTC, haammar-ledger commented on src/families/polkadot/types.js
> +  rewards: BigNumber,
Can be renamed `pendingRewards` indeed

2020-09-28 09:33 UTC, rjarasson-ledger approved these changes

2020-09-28 09:33 UTC, merged